Initial
edgefarm/edgefarm-application-sdk.py pull request #1
Opened 2021-06-07 06:18 UTC by KlausPopp

Currently supported
[x] ADS publishing
[x] ALM MQTT Module Communication

2021-06-07 06:23 UTC, siredmar requested changes

2021-06-07 06:23 UTC, siredmar commented on .vscode/settings.json
> +}
add .vscode to gitignore

2021-06-07 06:23 UTC, siredmar commented on README.md
> +```python
is it python2 or python3 or python3 only?

2021-06-08 19:35 UTC, batthebee requested changes

2021-06-08 19:35 UTC, batthebee commented on edgefarm_sdk/ads/producer.py
> +
missing schema_version and data

2021-06-08 19:35 UTC, batthebee commented on edgefarm_sdk/alm/mqtt_module/client.py
> +    def __init__(self, edgefarm_app):
missing comments for edgefarm_app, why is it necessary?

2021-06-08 19:35 UTC, batthebee commented on edgefarm_sdk/edgefarm_app.py
> +    """
missing parameter description in comments

2021-06-08 19:35 UTC, batthebee commented on edgefarm_sdk/edgefarm_app.py
> +class EdgefarmApp:
If you need a Singleton, you can implement this as module instead of an class

2021-06-08 19:35 UTC, batthebee commented on edgefarm_sdk/edgefarm_app.py
> +class EdgefarmApp:
I would prefer the name AlmModule instead of EdgefarmApp

2021-06-08 19:35 UTC, batthebee commented on edgefarm_sdk/alm/mqtt_module/client.py
> +    def _load_schemas(self):
there is another method load_schema, which solves the same topic

2021-06-09 07:50 UTC, KlausPopp commented on edgefarm_sdk/ads/ads_schemas/ads_data.avsc
> +{
Remove schemas. Fetch specific commit id in Makefile

2021-06-09 07:58 UTC, KlausPopp commented on edgefarm_sdk/ads/producer.py
> +    payload_schemas: A list of schema names you want to use to encode your payload
Separate encoder

2021-06-09 07:58 UTC, KlausPopp commented on edgefarm_sdk/ads/producer.py
> +                    "schema": payload_schema + ".avsc",
Future...

2021-06-09 08:07 UTC, KlausPopp commented on edgefarm_sdk/alm/mqtt_module/client.py
> +    def __init__(self, edgefarm_app):
Introduce network init.
Hide application name and module ID from customer

2021-06-09 08:14 UTC, KlausPopp commented on README.md
> +A python library for EdgeFarm applications.
Add folders to domains

2021-06-09 08:17 UTC, KlausPopp commented on edgefarm_sdk/ads/producer.py
> +
Add comment

2021-06-09 08:21 UTC, KlausPopp commented on edgefarm_sdk/alm/mqtt_module/client.py
> +    def _load_schemas(self):
factor out in separate module

2021-06-09 14:25 UTC, KlausPopp commented on .vscode/settings.json
> +}
removed

2021-06-09 14:27 UTC, KlausPopp commented on README.md
> +```python
Only Python3. And since asyncio API has changed in 3.6, I would support only recent versions (>=3.8)

2021-06-09 14:27 UTC, KlausPopp commented on edgefarm_sdk/__init__.py
> +# Copyright © 2021 edgefarm.io
Done

2021-06-09 14:34 UTC, KlausPopp commented on edgefarm_sdk/ads/ads_schemas/ads_data.avsc
> +{
Done

2021-06-09 14:34 UTC, KlausPopp commented on .env
> +export PYTHONPATH=./edgefarm_sdk:${PYTHONPATH}
Removed

2021-06-10 08:24 UTC, KlausPopp commented on edgefarm_sdk/ads/producer.py
> +    """A class to publish messages from an edgefarm application to edgefarm ADS
Done

2021-06-10 08:25 UTC, KlausPopp commented on edgefarm_sdk/ads/producer.py
> +    payload_schemas: A list of schema names you want to use to encode your payload
Done. AdsEncoder is no longer part of AdsProducer

2021-06-10 08:25 UTC, KlausPopp commented on edgefarm_sdk/ads/producer.py
> +                    "schema": payload_schema + ".avsc",
Not done. Future

2021-06-10 08:25 UTC, KlausPopp commented on edgefarm_sdk/ads/producer.py
> +class AdsProducer:
AdsEncoder can now be used standalone

2021-06-10 08:36 UTC, KlausPopp commented on README.md
> +A python library for EdgeFarm applications.
Done

2021-06-10 08:36 UTC, KlausPopp commented on edgefarm_sdk/ads/producer.py
> +                    "sequenceNumber": self.sequence_number,
In future

2021-06-10 08:36 UTC, KlausPopp commented on edgefarm_sdk/ads/producer.py
> +        def version_to_bin(version):
Done

2021-06-10 08:37 UTC, KlausPopp commented on edgefarm_sdk/ads/producer.py
> +
Done

2021-06-10 08:41 UTC, KlausPopp commented on edgefarm_sdk/edgefarm_app.py
> +    """
Done

2021-06-10 08:41 UTC, KlausPopp commented on edgefarm_sdk/edgefarm_app.py
> +class EdgefarmApp:
Converted to singleton (alm_module)

2021-06-10 08:41 UTC, KlausPopp commented on edgefarm_sdk/edgefarm_app.py
> +class EdgefarmApp:
Done

2021-06-10 08:41 UTC, KlausPopp commented on edgefarm_sdk/alm/mqtt_module/client.py
> +    def _load_schemas(self):
Done

2021-06-11 14:40 UTC, KlausPopp commented
Superseeded by PR #2

2021-06-11 14:40 UTC, KlausPopp commented
Superseeded by PR #2

2021-06-14 12:39 UTC, batthebee requested changes

2021-06-14 12:39 UTC, batthebee commented on edgefarm_application_sdk/base/iotedge_twin.py
> +    _logger.info("Read twin: Twin content %s" % twin)
Can contain sensitive informations. Remove print(s) of device/module twins

2021-06-14 12:45 UTC, merged